In [2]:
import numpy as np 
import matrix


┌────────────────────────────────────────┐
│ 0.2950  0.4478  0.7139  0.5007  0.2558 │
│ 0.5106  0.2539  0.5082  0.1328  0.0892 │
│ 0.1001  0.2141  0.0623  0.3048  0.8598 │
│ 0.4316  0.1451  0.5780  0.6021  0.4643 │
│ 0.3513  0.5882  0.8352  0.6124  0.0072 │
└────────────────────────────────────────┘


In [4]:
#单位矩阵
a = np.eye(3)
print(a)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [8]:
b = np.random.random((3,3,3))
print(b)


[[[0.88706043 0.99755241 0.55509996]
  [0.90753485 0.97852193 0.80931599]
  [0.11861161 0.03063995 0.66605893]]

 [[0.11923198 0.25943615 0.51632011]
  [0.24082012 0.33026919 0.75505963]
  [0.68215656 0.91626827 0.65435182]]

 [[0.94582551 0.21856938 0.77077071]
  [0.2371943  0.91535519 0.43609881]
  [0.33045367 0.44187186 0.65270188]]]


In [9]:
#10*10随机数组
c = np.random.random((10,10))
matrix.print_matrix(c)
c_min , c_max = c.min() , c.max()
print(c_min,c_max)


┌────────────────────────────────────────────────────────────────────────────────┐
│ 0.3595  0.2864  0.1175  0.2380  0.1157  0.5831  0.0689  0.0480  0.0997  0.9649 │
│ 0.9895  0.1839  0.8018  0.7220  0.0095  0.8281  0.9431  0.8690  0.5053  0.4672 │
│ 0.0076  0.1865  0.5132  0.0577  0.3140  0.7952  0.3615  0.4689  0.7002  0.7619 │
│ 0.4382  0.8706  0.5927  0.4693  0.2733  0.3586  0.7590  0.6821  0.3300  0.5859 │
│ 0.9595  0.4159  0.1108  0.0526  0.4954  0.9068  0.0958  0.2601  0.1875  0.2278 │
│ 0.4105  0.1089  0.3013  0.2882  0.0854  0.6774  0.6385  0.4910  0.3604  0.5496 │
│ 0.9052  0.5917  0.9411  0.9673  0.0216  0.3138  0.0638  0.1703  0.2750  0.1058 │
│ 0.4482  0.9443  0.2246  0.8448  0.9412  0.6587  0.6405  0.1632  0.6036  0.7265 │
│ 0.9572  0.7277  0.8741  0.0407  0.6705  0.7394  0.2391  0.2869  0.1892  0.7197 │
│ 0.7803  0.7822  0.5029  0.4428  0.2979  0.0893  0.6620  0.3947  0.9745  0.4701 │
└────────────────────────────────────────────────────────────────────────────────┘
0.00

In [11]:
#创建一个长度为30的随机向量
d = np.random.random((30,))
print(d)
m = d.mean()#计算向量的平均值
print(m)

[0.14286943 0.79447991 0.36609654 0.19915118 0.84491709 0.46270185
 0.78439478 0.60516409 0.76402872 0.71386947 0.08331638 0.94621927
 0.20307419 0.54858863 0.59477079 0.9426191  0.82169958 0.82372979
 0.02034175 0.49133618 0.62264292 0.06178355 0.10829161 0.54345339
 0.74784572 0.55652539 0.42394926 0.84179194 0.14547571 0.47294503]
0.5226024416294837


### 语法解释
- e ：NumPy 数组变量
- [1:-1, 1:-1] ：二维切片操作

    第一个维度（行）： 1:-1 表示从第2行到倒数第2行（不包括最后一行）
    
    第二个维度（列）： 1:-1 表示从第2列到倒数第2列（不包括最后一列）

In [15]:
e = np.ones((10,10))
e[1:-1,1:-1] = 0
print('e=')
matrix.print_matrix(e)


e=
┌────────────────────────────────────────────────────────────────────────────────┐
│ 1.0000  1.0000  1.0000  1.0000  1.0000  1.0000  1.0000  1.0000  1.0000  1.0000 │
│ 1.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  1.0000 │
│ 1.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  1.0000 │
│ 1.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  1.0000 │
│ 1.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  1.0000 │
│ 1.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  1.0000 │
│ 1.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  1.0000 │
│ 1.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  1.0000 │
│ 1.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  1.0000 │
│ 1.0000  1.0000  1.0000  1.0000  1.0000  1.0000  1.0000  1.0000  1.0000  1.0000 │
└────────────────────────────────────────────────────────────────────────────────┘
