In [1]:
import numpy as np 
import matrix


In [4]:
#单位矩阵
a = np.eye(3)
print(a)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [8]:
b = np.random.random((3,3,3))
print(b)


[[[0.88706043 0.99755241 0.55509996]
  [0.90753485 0.97852193 0.80931599]
  [0.11861161 0.03063995 0.66605893]]

 [[0.11923198 0.25943615 0.51632011]
  [0.24082012 0.33026919 0.75505963]
  [0.68215656 0.91626827 0.65435182]]

 [[0.94582551 0.21856938 0.77077071]
  [0.2371943  0.91535519 0.43609881]
  [0.33045367 0.44187186 0.65270188]]]


In [9]:
#10*10随机数组
c = np.random.random((10,10))
matrix.print_matrix(c)
c_min , c_max = c.min() , c.max()
print(c_min,c_max)


┌────────────────────────────────────────────────────────────────────────────────┐
│ 0.3595  0.2864  0.1175  0.2380  0.1157  0.5831  0.0689  0.0480  0.0997  0.9649 │
│ 0.9895  0.1839  0.8018  0.7220  0.0095  0.8281  0.9431  0.8690  0.5053  0.4672 │
│ 0.0076  0.1865  0.5132  0.0577  0.3140  0.7952  0.3615  0.4689  0.7002  0.7619 │
│ 0.4382  0.8706  0.5927  0.4693  0.2733  0.3586  0.7590  0.6821  0.3300  0.5859 │
│ 0.9595  0.4159  0.1108  0.0526  0.4954  0.9068  0.0958  0.2601  0.1875  0.2278 │
│ 0.4105  0.1089  0.3013  0.2882  0.0854  0.6774  0.6385  0.4910  0.3604  0.5496 │
│ 0.9052  0.5917  0.9411  0.9673  0.0216  0.3138  0.0638  0.1703  0.2750  0.1058 │
│ 0.4482  0.9443  0.2246  0.8448  0.9412  0.6587  0.6405  0.1632  0.6036  0.7265 │
│ 0.9572  0.7277  0.8741  0.0407  0.6705  0.7394  0.2391  0.2869  0.1892  0.7197 │
│ 0.7803  0.7822  0.5029  0.4428  0.2979  0.0893  0.6620  0.3947  0.9745  0.4701 │
└────────────────────────────────────────────────────────────────────────────────┘
0.00

In [11]:
#创建一个长度为30的随机向量
d = np.random.random((30,))
print(d)
m = d.mean()#计算向量的平均值
print(m)

[0.14286943 0.79447991 0.36609654 0.19915118 0.84491709 0.46270185
 0.78439478 0.60516409 0.76402872 0.71386947 0.08331638 0.94621927
 0.20307419 0.54858863 0.59477079 0.9426191  0.82169958 0.82372979
 0.02034175 0.49133618 0.62264292 0.06178355 0.10829161 0.54345339
 0.74784572 0.55652539 0.42394926 0.84179194 0.14547571 0.47294503]
0.5226024416294837


### 语法解释
- e ：NumPy 数组变量
- [1:-1, 1:-1] ：二维切片操作

    第一个维度（行）： 1:-1 表示从第2行到倒数第2行（不包括最后一行）
    
    第二个维度（列）： 1:-1 表示从第2列到倒数第2列（不包括最后一列）

In [15]:
# 创建 10×10 的全1数组
e = np.ones((10,10))  # np.ones(shape) 生成指定形状的全1数组
# 将数组内部区域设置为0，保持边界为1
e[1:-1,1:-1] = 0  # 切片操作：1:-1 表示从第2个元素到倒数第2个元素，不包括边界
print('e=')  # 打印数组标签
matrix.print_matrix(e)  # 以矩阵风格打印处理后的数组


e=
┌────────────────────────────────────────────────────────────────────────────────┐
│ 1.0000  1.0000  1.0000  1.0000  1.0000  1.0000  1.0000  1.0000  1.0000  1.0000 │
│ 1.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  1.0000 │
│ 1.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  1.0000 │
│ 1.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  1.0000 │
│ 1.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  1.0000 │
│ 1.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  1.0000 │
│ 1.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  1.0000 │
│ 1.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  1.0000 │
│ 1.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  1.0000 │
│ 1.0000  1.0000  1.0000  1.0000  1.0000  1.0000  1.0000  1.0000  1.0000  1.0000 │
└────────────────────────────────────────────────────────────────────────────────┘


### 参数解释：
- f ：输入数组，需要被填充的原始数组
- pad_width=1 ：填充宽度，指定在数组每个维度的边缘添加的元素数量。值为 1 表示在每个维度的前后各添加 1 层元素
- mode='constant' ：填充模式，'constant' 表示使用常量值填充
- constant_values=0 ：当 mode 为 'constant' 时使用的填充值，这里设置为 0
### 其他填充模式：
- 'edge' ：使用数组边缘值填充
- 'reflect' ：镜像反射填充
- 'wrap' ：循环填充
- 'symmetric' ：对称填充

In [3]:
#对于一个数组，如何用0填充边界
f = np.ones((3,8))
f = np.pad(f,pad_width = 1,mode = 'constant',constant_values = 0)
matrix.print_matrix(f)



┌────────────────────────────────────────────────────────────────────────────────┐
│ 0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000 │
│ 0.0000  1.0000  1.0000  1.0000  1.0000  1.0000  1.0000  1.0000  1.0000  0.0000 │
│ 0.0000  1.0000  1.0000  1.0000  1.0000  1.0000  1.0000  1.0000  1.0000  0.0000 │
│ 0.0000  1.0000  1.0000  1.0000  1.0000  1.0000  1.0000  1.0000  1.0000  0.0000 │
│ 0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000 │
└────────────────────────────────────────────────────────────────────────────────┘


np.nan 是 NumPy 中表示"不是一个数字"（Not a Number）的特殊值，它具有以下特点：

### 定义与本质
- 全称 ：Not a Number（非数字）
- 类型 ：特殊的浮点数
- 标准 ：遵循 IEEE 754 浮点数标准
### 核心特性
1. 不等于自身 ： np.nan == np.nan 返回 False ，这是它最独特的特性
2. 传播性 ：任何与 np.nan 的运算结果都是 np.nan
3. 比较结果 ：任何与 np.nan 的比较运算（>, <, ==, !=）都返回 False
4. 表示缺失值 ：常用于表示数据中的缺失或无效值

In [4]:
# 任何数与 np.nan 相乘结果都是 np.nan（Not a Number）
print("0 * np.nan:", 0 * np.nan)  # 结果: nan
# np.nan 是唯一一个不等于自身的值，这是 IEEE 754 浮点数标准的规定
print("np.nan == np.nan:", np.nan == np.nan)  # 结果: False
# 任何与 np.nan 的比较运算结果都是 False
print("np.inf > np.nan:", np.inf > np.nan)  # 结果: False
# 任何涉及 np.nan 的运算结果都是 np.nan
print("np.nan - np.nan:", np.nan - np.nan)  # 结果: nan
# 浮点数精度问题：3 * 0.1 实际结果不是精确的 0.3
print("0.3 == 3 * 0.1:", 0.3 == 3 * 0.1)  # 结果: False
# 显示 3 * 0.1 的实际计算结果
print("3 * 0.1:", 3 * 0.1)  # 结果: 0.30000000000000004


0 * np.nan: nan
np.nan == np.nan: False
np.inf > np.nan: False
np.nan - np.nan: nan
0.3 == 3 * 0.1: False
3 * 0.1: 0.30000000000000004


1. 第二个参数 ： k = -1
   
   - k 表示对角线的位置
   - k = 0 ：主对角线（默认值）
   - k > 0 ：主对角线以上的对角线（如 k=1 是主对角线上方第一条）
   - k < 0 ：主对角线以下的对角线（如 k=-1 是主对角线下方第一条）
### 函数用法
np.diag(v, k=0) 函数的作用：

- 当 v 是 一维数组 时：创建一个方阵，将 v 的元素放在指定对角线 k 上，其余位置为0
- 当 v 是 二维数组 时：提取 v 中指定对角线 k 的元素，返回一维数组

In [5]:
g = np.diag(1 +np.arange(4),k = -1)
matrix.print_matrix(g)

┌────────────────────────────────────────┐
│ 0.0000  0.0000  0.0000  0.0000  0.0000 │
│ 1.0000  0.0000  0.0000  0.0000  0.0000 │
│ 0.0000  2.0000  0.0000  0.0000  0.0000 │
│ 0.0000  0.0000  3.0000  0.0000  0.0000 │
│ 0.0000  0.0000  0.0000  4.0000  0.0000 │
└────────────────────────────────────────┘


In [11]:
h = np.zeros((8,8),dtype=int)# 创建一个8x8的零矩阵,元素为整数.
h[0::2,::2] = 1 #从行开始 
h[::2,1::2] = 1 #从列开始 
matrix.print_matrix(h)
print(h)


┌────────────────────────────────────────────────────────────────┐
│ 1.0000  1.0000  1.0000  1.0000  1.0000  1.0000  1.0000  1.0000 │
│ 0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000 │
│ 1.0000  1.0000  1.0000  1.0000  1.0000  1.0000  1.0000  1.0000 │
│ 0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000 │
│ 1.0000  1.0000  1.0000  1.0000  1.0000  1.0000  1.0000  1.0000 │
│ 0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000 │
│ 1.0000  1.0000  1.0000  1.0000  1.0000  1.0000  1.0000  1.0000 │
│ 0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000  0.0000 │
└────────────────────────────────────────────────────────────────┘
[[1 1 1 1 1 1 1 1]
 [0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 1]
 [0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 1]
 [0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 1]
 [0 0 0 0 0 0 0 0]]


In [16]:
np.unravel_index(100,(6,7,8))

(np.int64(1), np.int64(5), np.int64(4))