In [2]:
import numpy as np
import matrix 


In [4]:
#use tile function toact create a 8*8 matrix with 1 and 0

a = np.tile(np.array([[0,1],[1,0]]),(4,4))
matrix.print_matrix(a)


┌────────────────────────────────────────────────────────────────┐
│ 0.0000  1.0000  0.0000  1.0000  0.0000  1.0000  0.0000  1.0000 │
│ 1.0000  0.0000  1.0000  0.0000  1.0000  0.0000  1.0000  0.0000 │
│ 0.0000  1.0000  0.0000  1.0000  0.0000  1.0000  0.0000  1.0000 │
│ 1.0000  0.0000  1.0000  0.0000  1.0000  0.0000  1.0000  0.0000 │
│ 0.0000  1.0000  0.0000  1.0000  0.0000  1.0000  0.0000  1.0000 │
│ 1.0000  0.0000  1.0000  0.0000  1.0000  0.0000  1.0000  0.0000 │
│ 0.0000  1.0000  0.0000  1.0000  0.0000  1.0000  0.0000  1.0000 │
│ 1.0000  0.0000  1.0000  0.0000  1.0000  0.0000  1.0000  0.0000 │
└────────────────────────────────────────────────────────────────┘


 np.tile 函数用于重复数组

 第一个参数 np.array([[0,1],[1,0]]) 是基础数组，一个 2x2 的矩阵

第二个参数 (4,4) 表示在第一个维度（行）重复 4 次，在第二个维度（列）重复 4 次

 最终生成一个 8x8 的矩阵（2*4=8 行，2*4=8 列）

# 特征归一化（Min-Max 归一化）
- 方法 ：将特征值缩放到 [0,1] 范围
- 公式 ： $x' = \frac{x - x_{min}}{x_{max} - x_{min}}$
- 应用 ：神经网络输入、需要范围约束的算法

$\sqrt{\sum_{i=1}^{n} x_i^2}$


In [ ]:
#归一化：
b = np.random.random((5,5))
data_max, data_min = np.max(b), np.min(b)
b = (b - data_min) / (data_max - data_min)
matrix.print_matrix(b)
#验证归一化，求矩阵的模长
norm = np.linalg.norm(b)#矩阵的模长,原理是将矩阵的每个元素平方后平方和再开平方根：
print(norm)


┌────────────────────────────────────────┐
│ 0.5486  0.2542  0.8171  0.3653  0.5142 │
│ 0.5070  0.3619  0.2074  0.3870  0.7281 │
│ 0.3472  0.4381  0.5197  0.2563  0.5189 │
│ 1.0000  0.6772  0.9007  0.0000  0.1888 │
│ 0.7349  0.2486  0.6346  0.3151  0.4691 │
└────────────────────────────────────────┘
2.66248033675267


In [12]:
#创建一个将颜色描述为（RGBA）四个无符号字节的自定义dtype
color = np.dtype([("r",np.ubyte,1),("g",np.ubyte,1),("b",np.ubyte,1),("a",np.ubyte,1)])
color

dtype([('r', 'u1', (1,)), ('g', 'u1', (1,)), ('b', 'u1', (1,)), ('a', 'u1', (1,))])

In [14]:
c = np.dot(np.ones((5,3)),np.ones((3,2)))
matrix.print_matrix(c)

┌────────────────┐
│ 3.0000  3.0000 │
│ 3.0000  3.0000 │
│ 3.0000  3.0000 │
│ 3.0000  3.0000 │
│ 3.0000  3.0000 │
└────────────────┘


In [20]:
data = np.arange(10)
data [(3<data)&(data<8)]*=-1
print(data)


[ 0  1  2  3 -4 -5 -6 -7  8  9]


In [ ]:
print(sum(range(5),-1))  
from numpy import * #作用 ：导入 NumPy 库的所有函数和变量，会覆盖 Python 内置的同名函数（如 sum ）
print(sum(range(5),-1))  #负数表示从末尾计数 ： axis=-1 表示 最后一个轴




9
10


range(n)的意思是：生成一个序列，序列中的元素是从0开始的整数，直到指定的结束值n。

计算轴（axis） 是 NumPy 中用于指定 沿着哪个维度进行计算 的参数，它是理解 NumPy 数组操作的核心概念。

### 轴的定义
- 轴是数组的维度 ：
  - 一维数组只有 1 个轴（axis=0）
  - 二维数组有 2 个轴（axis=0：行方向，axis=1：列方向）
  - 三维数组有 3 个轴（axis=0：深度，axis=1：行，axis=2：列）
- 负数表示从末尾计数 ： axis=-1 表示 最后一个轴

In [ ]:
#找交集
data  = np.random.randint(0,10,10)# 生成 10 个 [0, 10) 范围内的随机整数
data1 = np.random.randint(0,10,10)
print(data)
print(data1)
print(np.intersect1d(data,data1))#交集


[8 3 6 1 1 8 1 0 5 5]
[8 5 1 1 8 4 2 4 9 5]
[1 5 8]


In [7]:
#如何从零位对浮点数做舍入
data  = np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(data)),data))

[ -5.  -5. -10.   9.  10.   6.   9. -10.  10. -10.]
